### ISSUE TITLE
Instructions to build the go application

### ISSUE THREAD

**Issue by cmoulliard** [openshift-evangelists/openshifter#14]
Can you add the Instructions to build the go application of openshifter (Linux, MacOs) or to generate them as binary under release section ?

**Comment by mhausenblas** [comment]
Yes, and in fact I'm working already in the `wip-mh9` branch on it, see https://github.com/openshift-evangelists/openshifter/blob/wip-mh9/contrib.md

**Comment by marekjelen** [comment]
Tracking in #24 as well.

**Comment by marekjelen** [comment]
Closing this as it's not relevant to Python, the recommended and supported way to use the tool is using the provided container.
