### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by saturnism** [openshift-evangelists/openshifter#3]
please vendor dependencies :)

**Comment by mhausenblas** [comment]
Yeah, vendoring is certainly a good point. However, for now, I intentionally did not do it because I was hoping `golang/dep` will establish itself very soon, rather than using something else in the meantime. Not sure, but maybe it's time to jump into the deep end ;)

**Comment by marekjelen** [comment]
Not relevant for Python.
