### ISSUE TITLE
Enrich documentation to detail the full process to create a VM on Google Cloud Platform

### ISSUE THREAD

**Issue by cmoulliard** [openshift-evangelists/openshifter#30]
Enrich documentation to detail the full process to setup a Google Cloud Project, setup the permissions/quotas, ... as described here -

https://github.com/cmoulliard/gce-openshifter

I propose to share my content completely or partially like also the bash scripts needed to automate the creation process

**Comment by marekjelen** [comment]
Closing as this was mostly committed.
