### ISSUE TITLE
Make the python branch master

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/openshifter#35]
And possibly archive the master branch as go version.

Since most of the development will now happen in the python branch.

**Comment by marekjelen** [comment]
+1 once we do deploy few clusters with the python version and catch the worst bugs will switch it over

**Comment by jorgemoralespou** [comment]
@marekjelen I've deployed 2, and no issue. One comment though, to avoid provisioning errors, could be to do some pre-flight checks:
- Check syntax of yaml is valid. I got this one yesterday
- Check that values are valid.
- Check for available quota beforehand?

I can open these as issues, so we track them, if we do see value.

**Comment by marekjelen** [comment]
Closing in favour of #44 and #45
