### ISSUE TITLE
Support CRI-O as the default runtime option

### ISSUE THREAD

**Issue by mhausenblas** [openshift-evangelists/openshifter#46]
Once OpenShift on CRI-O is ready for prime time (ATM a dependency with Ansible makes it awkward to install) then we should have CRI-O as the default runtime. Pointers:

- https://medium.com/cri-o/how-to-test-cri-o-with-openshift-container-platform-3-6-and-red-hat-enterprise-linux-7-4-60986fdf6861
- Kelsey is updating https://github.com/kelseyhightower/kubernetes-the-hard-way to show how CRI-O can be used (ETA: 8/31)

**Comment by marekjelen** [comment]
This will come automagically with some future release through the Ansible installer.
