### ISSUE TITLE
Do we need 100GB boot disk?

### ISSUE THREAD

**Issue by tqvarnst** [openshift-evangelists/openshifter#48]
If the boot disk is 100GB you will very quickly run into disk quota problems. I understand that 10 (which was the previous default) may a bit small, but 20 or 25 GB should be enough. Especially since the docker images are stored on a separate disk.

**Comment by marekjelen** [comment]
Even though Docker is put on separate disk, OpenShift uses the main disk for `emptyDir` PVs including the one used by registry. With many students building and pushing images, it grows pretty fast.

**Comment by tqvarnst** [comment]
Even though I think 100 GB is a lot we can close this now because the solution for #49 shows that you can configure that. Thanks
