### ISSUE TITLE
Setting the docker storage has no effect

### ISSUE THREAD

**Issue by tqvarnst** [openshift-evangelists/openshifter#49]
It seems that even if I set the disk size for the docker storage as suggested in the sample.yml it has no effect. The disk will be 100GB regardless.

**Comment by marekjelen** [comment]
Fixed in ca96e4c

**Comment by tqvarnst** [comment]
Please note that there is an issue with ca96e4c where it checks for 'size' instead of 'docker' and 'boot' here https://github.com/openshift-evangelists/openshifter/blob/master/openshifter/deployment.py#L53 and here https://github.com/openshift-evangelists/openshifter/blob/master/openshifter/deployment.py#L56, which again will only allow of the default values (100GB) to be used.

**Comment by marekjelen** [comment]
Fixed in  18b70ec
