### ISSUE TITLE
Configuration parameters for boot and disk are over rider with default value

### ISSUE THREAD

**Issue by tqvarnst** [openshift-evangelists/openshifter#50]
The solution to issue #49 introduced another issue where it checks for 'size' instead of 'docker' and 'boot' here https://github.com/openshift-evangelists/openshifter/blob/master/openshifter/deployment.py#L53 and here https://github.com/openshift-evangelists/openshifter/blob/master/openshifter/deployment.py#L56, which again will only allow of the default values (100GB) to be used.

**Comment by marekjelen** [comment]
Fixed in 18b70ec
