### ISSUE TITLE
SSH host key checking

### ISSUE THREAD

**Issue by marekjelen** [openshift-evangelists/openshifter#6]
For the use-case of the tool we ignore host key checking, as GCE very often gives the same IP address when tearing down and setting up the cluster in a short period of time and asking the user for validating the change of the a HostKey would be counter-productive.

IMHO in the case we prefer simplicity over strict security.

@mhausenblas @jorgemoralespou what do you think?

**Comment by jorgemoralespou** [comment]
I trust your opinion.

**Comment by mhausenblas** [comment]
Yes, simplicity rules in our case

**Comment by marekjelen** [comment]
As the other issue is not relevant with the new version and we agreed not to do host-checking, closing this issue as well.
