### ISSUE TITLE
When using installer:ocu you can not deploy eventbrite or create random users.

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/openshifter#64]
As there's ocu_blocker none of the setup steps are run, hence you can not create users or random users, or runasroot, or any execute action.

**Comment by jorgemoralespou** [comment]
And if this is the intent, we need to clearly document

**Comment by marekjelen** [comment]
It's kind of a safe-guard as I did not have time to validate if the `setup` stage is compatible with `ocu`.
