### ISSUE TITLE
Multitenant SDN by default

### ISSUE THREAD

**Issue by marekjelen** [openshift-evangelists/openshifter#7]
Let's use the multi-tenant plugin for OpenShift's SDN instead of subnet.

https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L562

This issue collects information, pros and cons of doing so.

**Comment by mhausenblas** [comment]
@marekjelen does https://github.com/osevg/openshifter/commit/d35c5123aca73d81676ea83d9bd3c7daf612503a address this issue here?

**Comment by marekjelen** [comment]
Yes, updated the template to use multi-tenant as there should be no drawbacks for us and will provide more "real world" set up.

**Comment by mhausenblas** [comment]
OK, thanks for the clarification @marekjelen. Any reason not to close it then?
