### ISSUE TITLE
Numeric sequence for generic users

### ISSUE THREAD

**Issue by marekjelen** [openshift-evangelists/openshifter#9]
This generates ASCII sequence and not numerical sequence

https://github.com/osevg/openshifter/blob/master/setup.go#L65

**Comment by cmoulliard** [comment]
Result is `user^A:$apr1$tsQ7SoBx$xVDy1d95SJmRSypgT28uz0`

**Comment by marekjelen** [comment]
weird, I was pretty sure I fixed that already ... https://github.com/openshift-evangelists/openshifter/blob/master/setup.go#L76

**Comment by cmoulliard** [comment]
Your syntax is correct
![screenshot 2017-06-08 11 08 00](https://user-images.githubusercontent.com/463790/26920962-e01a8984-4c3a-11e7-9219-dc203f17c18b.png)

**Comment by marekjelen** [comment]
Fixed in 05765e9a1889f701384daa5ebffa2f1c80ba05a0
